### ISSUE TITLE
Ability to add custom permanent tracks

### ISSUE THREAD

**Issue by spacemessenger** [scottbenton/Iron-Journal#420]
Some third party content for Ironsworn requires the use of new permanent stat tracks similar to Health, Momentum, Supply, etc. For example, the Arcanum supplement by Ulfengaard Gaming uses a Chaos Level track. It would be great if we could create these kinds of tracks so that they're always visible at the top of the character sheet.

**Comment by scottbenton** [comment]
Hello @spacemessenger!
This is already possible - from the "Settings" tab of your character, or via the "Settings" tab of your Campaign GM Screen, you can click the "Add Custom Track" button in order to add a new ability track.

If you are interested in trying out a more fully featured homebrew system, you can click the settings icon, select "Beta Tests", and turn on the homebrew beta test there that allows you to create these tracks and more!

Let me know if you run into any issues!

**Comment by spacemessenger** [comment]
Incredible! That's why this is the best digital character sheet for Ironsworn! Thanks a ton!
