### ISSUE TITLE
"Background Assets" Oracle is missing the values from the "Assets" column

### ISSUE THREAD

**Issue by tslays** [scottbenton/Iron-Journal#423]
Currently the "background assets" oracle is only showing you the "background" column of the oracle. Can the "assets" column be added to the result? Otherwise you will always have to cross-reference the rulebook.

e.g. Rolling a 90 on "Background Assets" Oracle is showing "Starship Engineer". It would be more helpful if the result would be "Starship Engineer GEARHEAD; TECH"

**Comment by scottbenton** [comment]
This will be fixed in the next full version of Iron Fellowship and Crew Link - there are a bunch of updates to the structure of data, and I've confirmed that this is fixed as a part of those changes. 

You can preview these changes by clicking the settings icon, clicking "Beta tests", and enabling the new Homebrew Content page.
