### ISSUE TITLE
Locations- Attempting to open them and the page freezed up.

### ISSUE THREAD

**Issue by orcwbigstick** [scottbenton/Iron-Journal#495]
I'm not sure about the best formatting for this- I've got an issue with locations. I've been experimenting using iron fellowship to see about running a game on there with a friend of mine in another state.
When I go to locations and click on any of them, it now locked up the page- it becomes unresponsive. I'm not sure how to fix it. I'll share the link below:
https://iron-fellowship.scottbenton.dev/worlds/Rq8nChsRdOBYchrZ5wR1?tab=locations

Please let me know what I can try to do to get this fixed up.

Thanks!

**Comment by scottbenton** [comment]
Should be fixed! Let me know if you see any more issues! @orcwbigstick

**Comment by orcwbigstick** [comment]
Wow, cool! Was this some sort of strong hit on some sort of fate weaving spell? :D Thanks @scottbenton

**Comment by scottbenton** [comment]
@orcwbigstick - I used to have a bug (fixed July 4th) that allowed you to stack locations in an infinite loop, so that location A could have location B as a child, which could have location A as a child. I fixed the issue, but I think a few people might have stuck locations. I fixed yours up directly through the database, but I'll investigate a larger fix for everyone.
