### ISSUE TITLE
Allow GMs to create custom moves

### ISSUE THREAD

**Issue by scottbenton** [scottbenton/Iron-Journal#60]
GMs and solo players should be able to create custom moves for their campaigns and characters.
In a campaign, we should create a new collection for these settings. Perhaps `/campaigns/${campaignId}/settings/moves`
For a solo player, we should create a new collection for these settings. Perhaps `/characters/${uid}/characters/${characterId}/settings/moves`

These moves should be displayed in the moves list under a "Custom Moves" category at the bottom.

**Comment by cptleo92** [comment]
Hi @scottbenton, I wanted to ask for some quick clarification before working on this. 

I'm wondering why there are two different types of custom moves. Do I have the right idea? 

- GMs can create a custom "campaign move". All characters participating in that campaign have access to these custom moves.
- Players can add custom "character moves" to their characters, which can only be used if they're in a campaign by themselves. Otherwise, they're just not shown in the moves list.

**Comment by scottbenton** [comment]
Yeah pretty much it! Ironsworn can be played solo, so I just want to make sure that solo players can add custom moves if they need to as well. Characters in a campaign should inherit any custom moves from the GM instead, so we can store those at the campaign level.
